name             'adminer'
maintainer       'Mojzis Stupka'
maintainer_email 'stupka@cngroup.dk'
license          'MIT'
description      'Installs/Configures adminer'
long_description 'Installs/Configures adminer http://www.adminer.org/'
version          '0.3.0'
