name             'adminer'
maintainer       'YOUR_NAME'
maintainer_email 'YOUR_EMAIL'
license          'All rights reserved'
description      'Installs/Configures adminer'
long_description 'Installs/Configures adminer'
version          '0.1.0'
